Load and Format Prompt

In [15]:
PROMPT_PATH = "L_and_I_Prompt_ENACTING.txt"
with open(PROMPT_PATH, "r") as file:
    prompt_raw = file.read()

In [22]:
# Used to separate system message 
SPLIT_STRING = "\n[***NEW_MESSAGE***]\n"

# Split the raw prompt text into 3 sections
prompt_split = prompt_raw.split(SPLIT_STRING)

# Ensure the prompt file format is correct
assert len(prompt_split) == 3, "Prompt file format incorrect."

In [24]:
# Convert prompt components to Amplify message format(json)
messages = [
    {"role": "system", "content": prompt_split[0].strip()},
    {"role": "user", "content": prompt_split[1].strip()},
    {"role": "assistant", "content": prompt_split[2].strip()}
]

# (Optional)Print to verify structure
for m in messages:
    print(m)

{'role': 'system', 'content': 'You are a helpful research assistant whose job it is to identify segments of students\' self-regulated learning (SRL) behaviors using multimodal data of them interacting with a mixed-reality embodied learning environment. Specifically, your job is to identify segments where students are demonstrating the ENACTING behavior.\n\nThis work focuses on the photosynthesis model. Participants\' movements are displayed on a projector screen while students embody different molecules as they move around the classroom. The environment features a mouse and a tomato plant with zoomed-in chloroplasts and roots (areas that cause molecule transformations). Students must move towards these areas to model interactions between the molecules they are embodying (oxygen, water, water-thinking, sugar and carbon dioxide) and the features on the screen. As students move, their states change, and they learn about the process of photosynthesis.\n\nFor example, one student may be assigned to begin the sequence as a CO2 molecule and must coordinate their movement with another participant playing as a water molecule. If these two participants meet at the enlarged chloroplast feature, the CO2 and water molecules convert to sugar and oxygen, respectively. The participant, now playing as the sugar molecule, must move to the plant\'s stem, and the simulation enlarges a leaf to indicate the plant is growing. Once at the stem, the participant receives a thought bubble displaying a water droplet to urge them to move to the roots, where they change into a water molecule. This participant can continue the sequence by pairing up with a CO2 molecule at the chloroplast. Once paired, he or she can convert to an O2 molecule and complete the sequence by providing this O2 to an animal (e.g., a mouse), prompting a state change to become a CO2 molecule. A student can be assigned any of the molecules and complete the sequence, returning to their initial molecule with sufficient coordination with the other players.\n\nData includes the following [MODALITIES] and their respective [LABELS]:\n\n[gaze]: where the student is looking\n\t[Screen]: the student is looking at the screen\n\t[Role] - [ID]: the student is looking at another human (either teacher, researcher, or student), specified via the other human\'s role and ID\n[movement]: whether or not the student is moving\n\t[moving]: the student is currently moving\n\t[stationary]: the student is not currently moving\n[action]: the student moves towards areas on the screen that can cause state transformations\n\t[chloroplast]: the student moved to the chloroplast\n\t[stem]: the student moved to the stem\n\t[mouse]: the student move to the mouse\n\t[roots]: the student moved to the roots\n[state]: the molecule the student transformed into\n\t[oxygen]: O2 molecule\n\t[carbon_dioxide]: CO2 molecule\n\t[sugar]: sugar molecule\n\t[waterthinking]: intermediate molecule (i.e., thought bubble) that suggests the student look for water\n\t[waterdrop]: H2O molecule\n\nYou will receive data in .csv format. Each row represents an EVENT. Events are sorted temporally by start_time (ascending) and structured as follows (actions and states do not have end_times because they are instantaneous):\nstart_time, end_time, modality, data\n\nStudents are considered to be ENACTING if and only if one of the following three Conditions is met, with one ENACTING segment spanning multiple EVENTS:\n\tCondition 1: The student is moving AND looking at the screen, i.e., [movement] = [moving] AND [gaze] = [Screen]\n\tCondition 2: The student is performing an action AND looking at the screen\n\tCondition 3: The student is changing state AND looking at the screen\n\nYour job is to identify all segments of ENACTING behaviors, i.e., individual segments where the ENACTING Conditions are taking place. You should output your responses in accordance with the following JSON schema, justifying your reasons for identifying each segment:\n\n{\n  "segments": [\n    {\n      "justification": "string",\n      "time_in": "HH:MM:SS", \n      "time_out": "HH:MM:SS",\n      "label": "string"\n    },\n    ...\n  ]\n}\n\nYou are to adhere to the following guidelines when generating your responses:\n1. For Conditions 2 and 3, because both [state] and [action] do not have end_times, the time_in for each segment will always be the start_time of [gaze], and the time_out will always be start_time of [action] (Condition 2) or [state] (Condition 3).'}
{'role': 'user', 'content': 'start_time,end_time,modality,data\n0:00:00,0:00:03,gaze,Screen\n0:00:00,0:00:03,movement,moving\n0:00:03,0:00:17,movement,stationary\n0:00:13,0:00:28,gaze,Screen\n0:00:17,0:00:24,movement,moving\n0:00:24,0:00:28,movement,stationary\n0:00:28,0:00:33,gaze,Student - EL\n0:00:28,0:00:47,movement,moving\n0:00:30,,action,chloroplast\n0:00:34,,action,chloroplast\n0:00:38,0:01:23,gaze,Screen\n0:00:40,,state,oxygen\n0:00:47,0:00:53,movement,stationary\n0:00:53,0:01:14,movement,moving\n0:00:57,,action,stem\n0:01:02,,action,mouse\n0:01:02,,state,carbon_dioxide\n0:01:05,,action,stem\n0:01:08,,action,chloroplast\n0:01:14,0:01:21,movement,stationary\n0:01:17,,state,sugar\n0:01:21,0:01:35,movement,moving\n0:01:23,0:01:28,gaze,Researcher - Sarah\n0:01:24,,action,stem\n0:01:24,,state,waterthinking\n0:01:27,,action,roots\n0:01:27,,state,waterdrop\n0:01:28,0:01:33,gaze,Student - DaPaw\n0:01:29,,action,stem\n0:01:33,0:01:35,gaze,Screen\n0:01:33,,action,chloroplast'}
{'role': 'assistant', 'content': '{\n  "segments": [\n    {\n      "justification": "During time 00:00:00 to 00:00:03, the student (Rose) has her [gaze] fixated on the [screen] and has [movement] equal to [moving]. Condition 1 states that if the student is moving and looking at the screen, then the student is ENACTING. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:00", \n      "time_out": "00:00:03",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:13 to 00:00:28. From time 00:00:17 to 00:00:24, the student\'s [movement] is equal to [moving]. Condition 1 states that if the student is moving and looking at the screen, then the student is ENACTING. Condition 1 is met on the intersection of Rose\'s gaze and movement from 00:00:17 to 00:00:24. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:17", \n      "time_out": "00:00:24",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:00:40, the student\'s [state] changes to [oxygen]. Condition 3 states that if the student changes state and is looking at the screen, then the student is ENACTING. Condition 3 is met on the intersection of Rose\'s gaze and state change from 00:00:38 to 00:00:40. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:00:40",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. From time 00:00:53 to 00:01:14, the student\'s [movement] is equal to [moving]. Condition 1 states that if the student is moving and looking at the screen, then the student is ENACTING. Condition 1 is met on the intersection of Rose\'s gaze and movement from 00:00:53 to 00:01:14. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:53", \n      "time_out": "00:01:14",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:00:57, the student takes an [action] by moving to the [stem]. Condition 2 states that if the student is performing an action and looking at the screen, then the student is ENACTING. Condition 2 is met on the intersection of Rose\'s gaze and action from 00:00:38 to 00:00:57. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:00:57",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:01:02, the student takes an [action] by moving to the [mouse]. Condition 2 states that if the student is performing an action and looking at the screen, then the student is ENACTING. Condition 2 is met on the intersection of Rose\'s gaze and action from 00:00:38 to 00:01:02. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:01:02",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:01:02, the student\'s [state] changes to [carbon_dioxide]. Condition 3 states that if the student changes state and is looking at the screen, then the student is ENACTING. Condition 3 is met on the intersection of Rose\'s gaze and state change from 00:00:38 to 00:01:02. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:01:02",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:01:05, the student takes an [action] by moving to the [stem]. Condition 2 states that if the student is performing an action and looking at the screen, then the student is ENACTING. Condition 2 is met on the intersection of Rose\'s gaze and action from 00:00:38 to 00:01:05. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:01:05",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:01:08, the student takes an [action] by moving to the [chloroplast]. Condition 2 states that if the student is performing an action and looking at the screen, then the student is ENACTING. Condition 2 is met on the intersection of Rose\'s gaze and action from 00:00:38 to 00:01:08. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:01:08",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. At time 00:01:17, the student\'s [state] changes to [sugar]. Condition 3 states that if the student changes state and is looking at the screen, then the student is ENACTING. Condition 3 is met on the intersection of Rose\'s gaze and state change from 00:00:38 to 00:01:17. By definition, this is an ENACTING segment.",\n      "time_in": "00:00:38", \n      "time_out": "00:01:17",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "From time 00:01:21 to 00:01:35, the student\'s [movement] is equal to [moving]. The student\'s (Rose\'s) [gaze] is fixated on the [Screen] from 00:00:38 to 00:01:23. Condition 1 states that if the student is moving and looking at the screen, then the student is ENACTING. Condition 1 is met on the intersection of Rose\'s movement and gaze from 00:01:21 to 00:01:23. By definition, this is an ENACTING segment.",\n      "time_in": "00:01:21", \n      "time_out": "00:01:23",\n      "label": "ENACTING"\n    },\n    {\n      "justification": "The student\'s (Rose\'s) [gaze] is fixated on the [Screen] at time 00:01:33. Also at time 00:01:33, the student takes an [action] by moving to the [chloroplast]. Condition 2 states that if the student is performing an action and looking at the screen, then the student is ENACTING. Condition 2 is met on the intersection of Rose\'s gaze and action at 00:01:33. By definition, this is an ENACTING segment.",\n      "time_in": "00:01:33", \n      "time_out": "00:01:33",\n      "label": "ENACTING"\n    }\n  ]\n}'}

Import data

In [28]:
import pandas as pd

DATA_PATH = "L&I - Student Mastersheet - EN-MESSI-D2.csv"

df = pd.read_csv(DATA_PATH)

# Convert all the NaN to the ''
df = df.fillna('')

# Convert instances of "not moving" to "stationary"
df["data"] = df["data"].replace("not moving", "stationary")

df.head()

  start_time end_time  modality                    data
0    0:00:00              state           waterthinking
1    0:00:00  0:00:05  movement              stationary
2    0:00:00  0:00:01      gaze  Student - Taylor Swift
3    0:00:06  0:00:09  movement                  moving
4    0:00:07  0:04:38      gaze                  Screen

In [30]:
# Filter dataframe where:
# 1. "modality" does not include gesture or speech
# 2. "gaze" only includes Screen
df_no_speech_or_gaze = df[~df["modality"].isin(["gesture", "speech"])]
assert set(df_no_speech_or_gaze.modality) == {'state', 'movement', 'action', 'gaze'}

df_no_speech_or_gaze_screen_only = df_no_speech_or_gaze[(df_no_speech_or_gaze["modality"] != "gaze") | \
        (df_no_speech_or_gaze["data"] == "Screen")]
assert all(df_no_speech_or_gaze_screen_only[df_no_speech_or_gaze_screen_only["modality"] == \
                                            "gaze"]["data"] == "Screen")
df_no_speech_or_gaze_screen_only.head(5)

  start_time end_time  modality           data
0    0:00:00              state  waterthinking
1    0:00:00  0:00:05  movement     stationary
3    0:00:06  0:00:09  movement         moving
4    0:00:07  0:04:38      gaze         Screen
5    0:00:08  0:00:14  movement     stationary

In [48]:
# Make data comma-separated form but in string
data_csv_string = df_no_speech_or_gaze_screen_only.to_csv(index=False)

data_csv_string_split = [s for s in data_csv_string.split('\n') if s]
assert len(data_csv_string_split) == len(df_no_speech_or_gaze_screen_only)+1,print(len(data_csv_string_split), len(df_no_speech_or_gaze_screen_only)+1)

# Debugging
# print(len(data_csv_string_split))
# for line in data_csv_string_split:
#     print(line)

In [52]:
# Rebuild messages cleanly every time

messages = [
    {"role": "system", "content": prompt_split[0].strip()},
    {"role": "user", "content": prompt_split[1].strip()},
    {"role": "assistant", "content": prompt_split[2].strip()},
    {"role": "user", "content": data_csv_string}
]

print("Message length:", len(messages))

Message length: 4

Inference

In [ ]:
# Inference via Vanderbilt Amplify API
import requests
import json

In [ ]:
#1.Configuration
BASE_URL = "https://prod2-api.vanderbilt.ai"   
AMP_TOKEN = "YOUR_AMP_TOKEN_HERE"             

headers = {
    "Authorization": f"Bearer {AMP_TOKEN}",
    "Content-Type": "application/json"
}

In [ ]:
##2.Build request payload
payload = {
    "data": {
        "temperature": 0,          # deterministic output
        "max_tokens": 4000,
        "messages": messages,      # the message list we built earlier
        "options": {
            "skipRag": True,       # disable RAG
            "ragOnly": False,
            "model": {
                "id": "GPT 5.2"     
            }
        }
    }
}

In [ ]:
##3.Send POST request

response = requests.post(
    f"{BASE_URL}/chat",
    headers=headers,
    json=payload
)

In [ ]:
##4. Check HTTP status
if response.status_code != 200:
    print("HTTP Status Code:", response.status_code)
    print("Error response:")
    print(response.text)
    raise Exception("Amplify request failed")

In [ ]:
##5. Parse JSON response

result = response.json()

print("Raw Amplify Response:")
print(result)

In [ ]:
##6. Extract model output
if result.get("success"):
    text_response = result["data"]  
else:
    raise Exception("Amplify returned failure:", result)

In [ ]:
##7.Convert JSON string to Python dict

parsed_json = json.loads(text_response)

print("Parsed JSON:")
print(parsed_json)

Save Response

import os
import json

RESULTS_PATH = ""

# Ensure directory exists
os.makedirs(os.path.dirname(RESULTS_PATH), exist_ok=True)

# Save JSON safely
with open(RESULTS_PATH, "w", encoding="utf-8") as f:
    json.dump(parsed_json, f, indent=4, ensure_ascii=False)

print("JSON successfully saved to:", RESULTS_PATH)